FROM maven:3.6-jdk-8 AS build

#设置为国内镜像源
RUN sed -i 's#</mirrors>#<mirror><id>alimaven</id><name>aliyun maven</name><url>http://maven.aliyun.com/nexus/content/groups/public/</url><mirrorOf>central</mirrorOf></mirror></mirrors>#g' /usr/share/maven/conf/settings.xml

#复制代码至tmp/code路径
COPY ./ /tmp/code

#安装并打包
#RUN (cd /tmp/code && mvn clean package -P test -nsu -Dmaven.test.skip=true)

#创建文件夹
RUN (mkdir /tmp/dependency && mkdir /tmp/dependency/jar  )

#复制JAR
RUN ( mv /tmp/code/target/*.jar /tmp/dependency/jar/app.jar)

#依赖自构建的OpenJDK环境
FROM registry.cn-shenzhen.aliyuncs.com/happyblocks/amatech-openjdk8:latest

#设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

#复制jar
ARG DEPENDENCY=/tmp/dependency
COPY --from=0 ${DEPENDENCY}/jar /app/

#启动指令
ENTRYPOINT ["java","-jar","/tmp/dependency/jar/app.jar"]

#暴露端口
EXPOSE 8080


